### ISSUE TITLE
Allow selecting any existing columns for export and import

### ISSUE THREAD

**Issue by briddle** [vojtasvoboda/oc-userimportexport-plugin#10]
Hi,

Great plugin but it would be awesome if you could add the possibility to allow selecting any existing columns for export and import. For instance, as is the case when using the User+ plugin or another plugin that has extended the User plugin.

**Comment by briddle** [comment]
Hi Voita,

I really like how your import/export plugin works but I would love it to recognise when I have added extra columns to the users table (e.g. the User+ plugin adds some columns). I would love the export and import functions of your plugin to allow me to select the custom columns that I have added (by reading the column names from the users table in the database). 

Thank you for an already great plugin!

Wiego

**Comment by vojtasvoboda** [comment]
Hi Wiego,

you have to override YAML configuration file: https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/userexport/columns.yaml

There is a step-by-step tutorial, how to do that: https://github.com/vojtasvoboda/oc-brands-plugin-override-example#add-new-columns-to-backend-list

Unfortunately there is nothing like 'automagically loading new columns'.

Good luck
Vojta

**Comment by briddle** [comment]
Hi Voita,

Overwriting the YAML configuration file will work for me, thanks :)

However, if I am not mistaking you can automagically get a list of the columns in a database table. You could show all these columns with checkboxes (as you do now based on YAML) and allow users to select the columns to export/import. See for example https://stackoverflow.com/questions/1054984/how-can-i-get-column-names-from-a-table-in-sql-server#1054988

This would also allow your less technical end-users to configure the export and import out of the box without the need to change configuration files with FTP or a code editor. In fact, this could allow your plugin to be used on any table in the database making it even more versatile.

Greetings!

**Comment by vojtasvoboda** [comment]
Yes it's possible, so feel free to send pull request and I will be more then happy to merge it to this plugin. Unfortunately I don't have free space to do that in near future.

Thank you
Vojta
