### ISSUE TITLE
Problems with code

### ISSUE THREAD

**Issue by Carrrven** [vojtasvoboda/oc-userimportexport-plugin#12]
"User not activated!" and Avatar not addet. Error with url

**Comment by vojtasvoboda** [comment]
"User not activated" - in CMS > Settings > Users > in Activation tab > check automatic activation.

Avatar - have you created `users` folder in media folder with images?

**Comment by Carrrven** [comment]
Hi. In media folder i created the folder `users` and have some error 

> "The file "/storage/ssd5/932/7556932/public_htmlhttp://some-domain.gom/storage/app/media/users/name.jpg" does not exist" on line 37 of /storage/ssd5/932/7556932/public_html/vendor/symfony/http-foundation/File/File.php

I solved the problem by removing the domain name in UserImportModel in this part `$pathinfo['dirname'] `

The automatic activation is checked but users addet not activated

**Comment by vojtasvoboda** [comment]
Hi @Carrrven I just release new version 1.0.5 fixes problem with the import avatars. Thanks for reporting the issue.
