### ISSUE TITLE
Send important Users a welcome email?

### ISSUE THREAD

**Issue by anthedue** [vojtasvoboda/oc-userimportexport-plugin#14]
Hi there, thank you so much for the plugin, creating the users works perfectly. However, when imported, they don't seem to be sent the welcome email. Activating them doesn't do that either. Do you know if there is a way to manually trigger that?

**Comment by vojtasvoboda** [comment]
Hello @anthedue, for send a welcome email, just uncomment this line in the plugin: https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/UserImportModel.php#L50
