### ISSUE TITLE
Import export documents

### ISSUE THREAD

**Issue by queengab** [vojtasvoboda/oc-userimportexport-plugin#2]
Hi Vojtas,
i'm using since six months october cms, now I am looking for solutions to develop an import procedure to October. I have to import text from 17 chapters. I want to take advantage of october cms structure. The idea is to create 17 pages and create for each paragraph a content contained in different folders.

Pages

chapter 1
chapter 2
chapter 3 eccc...

In Content area

chapter1

    paragraph 1
    paragraph 2
    paragraph 3

chapter2

    paragraph 1
    paragraph 2
    paragraph 3

Now how can we create a procedure that parses a rtf file with this (https://github.com/henck/rtf-html-php), creating in october each pages (chapter) and contents (paragraph) and fill all? Is there a batch procedure that creating pages and contents that can we use with this hypotethycal procedure?

I'm a webmanager but not a really can understand how to use apis to create an import and update procedure? Can you help me? We can share the results on october plugin page. 

Thansk very much
Gabriele

**Comment by vojtasvoboda** [comment]
Hello Gabriele,

at the first point let's clarify, that this plugin is only for Import/Export Users (managed by RainLab.User plugin). Not for importing any else objects.

If I wanted to import Pages or content blocks, I would use `RainLab\Pages\Classes\Page::create($data)` method and for importing content block just simple File object for creating plain file documents. For resolve theme path, you can use `Cms\Classes\Theme` - but I didn't test it :-)

Maybe you can find inspiration at Cms\Models\ThemeImport - it manage import content block without overwriting.

Wish you best for building import feature.
