### ISSUE TITLE
How do you import passwords?

### ISSUE THREAD

**Issue by jaysonfrazer** [vojtasvoboda/oc-userimportexport-plugin#8]
Hi there, great plugin! Just wondered how to import passwords. The Password field is not shown in the available database fields to match to.

**Comment by vojtasvoboda** [comment]
Hi Jayson, password are not included by default, but you can extend the config file and add fields as you want:

https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/userimport/columns.yaml

Thanks for using my plugin :-)

**Comment by jaysonfrazer** [comment]
That's awesome, thanks so much for the fast reply. Really like your plugin,
great job!

Kind regards
Jayson

Regards,
Jayson


*Jayson FrazerGeneral Manager*
*The Incentive Lab*
<jayson@theincentivelab.com>
8/395 Collins Street Melbourne Vic 3000
Direct: +613 9079 0901
Phone: +613 9079 0900
Fax: +613 9079 0929
<jayson@theincentivelab.com>Mobile +61 (0)402 927 855
jayson@theincent <jayson@theincentivelab.com> <jayson@theincentivelab.com>
ivelab.com <jayson@theincentivelab.com> <jayson@theincentivelab.com>
www.theincentivelab.com

YouTube Channel <https://www.youtube.com/channel/UCA_wIpODO0rW3nrdGnfr_kA>

**Comment by jaysonfrazer** [comment]
Hi Vojta,

One last question. What happens when a user is uploaded. Is an activation
email sent for them to confirm and set their password?

Regards,
Jayson


*Jayson FrazerGeneral Manager*
*The Incentive Lab*
<jayson@theincentivelab.com>
8/395 Collins Street Melbourne Vic 3000
Direct: +613 9079 0901
Phone: +613 9079 0900
Fax: +613 9079 0929
<jayson@theincentivelab.com>Mobile +61 (0)402 927 855
jayson@theincent <jayson@theincentivelab.com> <jayson@theincentivelab.com>
ivelab.com <jayson@theincentivelab.com> <jayson@theincentivelab.com>
www.theincentivelab.com

YouTube Channel <https://www.youtube.com/channel/UCA_wIpODO0rW3nrdGnfr_kA>

**Comment by vojtasvoboda** [comment]
Hi Jayson, check this plugin's line: https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/UserImportModel.php#L51

If you uncomment this line, imported users will be activated and welcome e-mails will be sent. If you don't want to send e-mails, just turn them off in backend settings:

![snimek obrazovky 2017-03-31 v 0 15 00](https://cloud.githubusercontent.com/assets/374917/24528524/24960446-15a7-11e7-90b1-1401d8519abf.png)

**Comment by jaysonfrazer** [comment]
Awesome, thanks so much for the help. really like your plugin and
appreciate your reply to my email. Have a great day!

Regards
Jayson

Regards,
Jayson


*Jayson FrazerGeneral Manager*
*The Incentive Lab*
<jayson@theincentivelab.com>
8/395 Collins Street Melbourne Vic 3000
Direct: +613 9079 0901
Phone: +613 9079 0900
Fax: +613 9079 0929
<jayson@theincentivelab.com>Mobile +61 (0)402 927 855
jayson@theincent <jayson@theincentivelab.com> <jayson@theincentivelab.com>
ivelab.com <jayson@theincentivelab.com> <jayson@theincentivelab.com>
www.theincentivelab.com

YouTube Channel <https://www.youtube.com/channel/UCA_wIpODO0rW3nrdGnfr_kA>

**Comment by vojtasvoboda** [comment]
Hi Jayson, if you like my plugin, please write me a review: https://octobercms.com/plugin/vojtasvoboda-userimportexport

It really helps me.

Thanks
Vojta

**Comment by jaysonfrazer** [comment]
Done!

Regards,
Jayson


*Jayson FrazerGeneral Manager*
*The Incentive Lab*
<jayson@theincentivelab.com>
8/395 Collins Street Melbourne Vic 3000
Direct: +613 9079 0901
Phone: +613 9079 0900
Fax: +613 9079 0929
<jayson@theincentivelab.com>Mobile +61 (0)402 927 855
jayson@theincent <jayson@theincentivelab.com> <jayson@theincentivelab.com>
ivelab.com <jayson@theincentivelab.com> <jayson@theincentivelab.com>
www.theincentivelab.com

YouTube Channel <https://www.youtube.com/channel/UCA_wIpODO0rW3nrdGnfr_kA>
