### ISSUE TITLE
Add Send Access to imported users

### ISSUE THREAD

**Issue by Ladylain** [vojtasvoboda/oc-userimportexport-plugin#9]
Hello, 

first, thanks for your work.

I would like to know if it's possible to send mail activation or mail access to clients that we just saved ? 

I have tryied to add the function sendInvitation() from User plugin but it's not working i think i miss something. 

could you help me ? 

Thanks

**Comment by vojtasvoboda** [comment]
Hi, yes it is possible, check this line in my plugin: https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/UserImportModel.php#L51

You can uncomment it and plugin will automatically send email. You can set this email in CMS > Backend > Settings > Users > Notification.

**Comment by Ladylain** [comment]
Hi, 

sorry to bother you again, but i already tried this uncomment tip. And unfortunately, it didn't worked, Moreover, i don't have any **CMS > Backend > Settings > Users > Notification** menu on my user backend, and i don't know why cause my _rainlab-user-plugin_ is up to date. 

Do you have another solution to give me ? 

thanks a lot for your help

**Comment by vojtasvoboda** [comment]
Since RainLab.User 1.4.0 you have to install [RainLab.Notify](https://octobercms.com/plugin/rainlab-notify) plugin to be able to send notifications (e-mails, SMS, ...).

**Comment by Ladylain** [comment]
Thanks a lot , you're the best !
